# Generated by Django 3.1 on 2021-12-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithChangedDefaultPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='modelwithcustompermissions',
            options={'permissions': (('can_deliver_pizzas', 'Can deliver pizzas'),), 'verbose_name': 'Model with default & custom permission'},
        ),
        migrations.AlterModelOptions(
            name='modelwithcustompermissionsnodefault',
            options={'default_permissions': (), 'permissions': (('can_do_stuff', 'Can do stuff'), ('can_do_more_stuff', 'Can do more stuff')), 'verbose_name': 'Model with no default permissions & 2 custom permissions'},
        ),
        migrations.AlterModelOptions(
            name='modelwithdefaultpermissions',
            options={'verbose_name': 'Model with all default permissions'},
        ),
        migrations.AlterModelOptions(
            name='modelwithediteddefaultpermission',
            options={'default_permissions': ('change',), 'verbose_name': 'Model with `change` permissions Only'},
        ),
    ]
