# Generated by Django 3.1 on 2021-12-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_auto_20211209_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelwithchangeddefaultpermissions',
            options={'default_permissions': ('view',)},
        ),
    ]
